name: Gatling Performance Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
    - name: Run Gatling Tests
      run: mvn gatling:test -Dgatling.simulationClass=com.example.spring_boot_gatling.BasicSimulation
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: gatling-results
        path: target/gatling
